name: release

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: go-semantic-release/action@v1
        with:
          allow-initial-development-versions: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
